// This file is generated

I_short_name_0 = [
", Daughter",
", Harriet (Enslaved)",
"Mcghee, Hazel",
", Son",
", Vicki Renee",
"Adams, Ayrenne",
"Adams, Dexter Jr.",
"Adams, Dexter Carter Sr,",
"Adams, Milton",
"Beatte, Luxe",
"Beatte, Shawn",
"Box, Dedrick",
"Box, DeShon",
"Wilson Box, Shavonica",
"Browning, Betty Jean",
"Bryant, Elizabeth",
"Caradine, Christian",
"Caradine, Corbin",
"Caradine, Dylann",
"Caradine, Dylann",
"Caradine, Hailey",
"Caradine, Jessica",
"Caradine Friend, Shari Rene",
"Caradine, Zacharia",
"Caradine, Zayire",
"Cotledge, Jackie",
"Cotledge, Paxton",
"Cotledge, Porchia",
"Davis, Bessie",
"Davis, Elyza",
"Davis, Gideon",
"Davis, Roy",
"Duval, Dominique",
"Newburn Duval, Joselyn",
"Eason, Charles",
"Eason, Dennis Sterlon",
"Newburn Eason, Deserea",
"Eason, Edward Emerson",
"Eason Nelson, Frances",
"Eason, Haven",
"Eason, Hazel",
"Eason, Hudson",
"Eason, Jennifer",
"Eason, Lillie Alma",
"Eason, Michael",
"Eason, Rodney William",
"Eason, Steve",
"Eason, Vance",
"Eason, VaShonda",
"Eason, Vivienne Monroe",
"Eason, Willie",
"Friend, Michael",
"Harris Knox, Lillian",
"Newburn Harrison, Evelyn",
"Harrison, Shunn",
"Harrison, Son1",
"Hill, Daughter 1",
"Hill, Madre",
"Hill, Son 2",
"Hill, Son 3",
"Hill, Son1",
"Hopkins Newburn, Brenda J.",
"Hunt, Rick",
"Johnson, Angela Anita",
"Jones, Mary Helen",
"Jones, Mary Jane",
"Jones, Unk",
"Knox, Altora",
"Knox, Amiziah J",
"Knox, Avery",
"Knox, Caldonia",
"Knox, Columbus Emerson",
"Knox Stroope, Daniel",
"Knox, Della",
"Knox, Douglas",
"Knox, Ed",
"Knox, Flora",
"Knox, Geneva",
"Knox, Harriett J",
"Knox, Isiah",
"Knox, Isom",
"Knox, Jacob",
"Knox, Jacob",
"Knox, James",
"Knox Stroope, Jane",
"Knox, Josiah",
"Knox Newburn, Josie Ella",
"Knox, Kathleen",
"Knox, Leo O",
"Knox, Margaret",
"Knox, Martha J",
"Knox Newburn, Mary Jane",
"Jones Knox, Mary Jane",
"Knox, Mattie Rae",
"Knox, Melissa",
"Knox, Nathan",
"Jones Knox, Nora L",
"Knox, Oddis",
"Knox, Oddis",
"Knox, Ransom",
"Knox, Richard",
"Knox, Robert J.",
"Knox, Roosevelt",
"Knox, Sarah Ann",
"Knox, Sevilla W",
"Knox, Suneva",
"Knox, Tametta",
"Knox, Tempe",
"Knox, Thelma",
"Knox, Themis",
"Knox, UNK",
"Knox, Vasser",
"Knox, William R",
"Knox, Zelma Marie",
"Knox Stroope, Isom",
"Leeper, T'Aisha",
"Leeper Wilson, Yvonne",
"Manica, Christopherr Benson",
"McCauley, Henry Clayburn",
"McCauley, Jesse Franklin",
"McCauley, Jessie Mack",
"McCauley, Roberrt Earl",
"Meyers, Barry L.",
"Wilson Meyers, Carolyn Sue",
"Morgan, Allan Cornell",
"Morgan, Ebony",
"Morgan, Ivory",
"Morgan, Marlon",
"Morgan, Valerie",
"Morrison, Shanea",
"Nelson, Desarea",
"Nelson, Emerie",
"Nelson, Mary Grace",
"Nelson, Terry Jr.",
"Nelson, Terry Sr.",
"Newborn, Halee",
"Newburn, 8/8 ?",
"Newburn, Albert",
"Newburn, Amanda",
"Newburn Deloach?, Amanda",
"Newburn, Anthony David",
"Newburn, Arthenia",
"Newburn, Ashley",
"Newburn, Aubrey Ray",
"Newburn, Barry",
"Newburn Seawood, Bernice",
"Newburn, Betty J.",
"Newburn, Betty Ruth",
"Newburn, Billy Charles",
"Newburn, Carl Edward",
"Newburn, Carrla",
"Newburn, Crystal",
"Newburn Cotledge, Deborah",
"Newburn, Delilah",
"Newburn, Demond",
"Newburn, Dena",
"Newburn, Derrick Byron",
"Newburn, Devolis",
"Newburn, Dorothy",
"Newburn, Doug",
"Newburn, Douglas Patten",
"Newburn, Earl Roosevelt",
"Newburn, Fallon",
"Newburn, Felix",
"Newburn Morgan, Flossie Rae",
"Newburn, Frank Delane",
"Newburn, Gloria",
"Newburn, Haja",
"Newburn Neal, Helen",
"Newburn, Henry Lee",
"Newburn, Jacyn Denzel",
"Newburn, James L.",
"Newburn, James Sylvester",
"Newburn, James Tanner",
"Newburn, Jason",
"Newburn, Jocelyn Akoyia",
"Newburn, Joel",
"Newburn, Joseph",
"Newburn, Joseph L",
"Newburn, Joseph Samuel",
"Newburn, Joseph Vass",
"Newburn, Josh A",
"Newburn, Joshua",
"Newburn Hogan, Juanita",
"Newburn, Justin",
"Newburn, Kenneth",
"Newburn, Kerry",
"Newburn, Larry",
"Newburn, Lenore",
"Newburn Owens,, Lillie",
"Newburn House, Mable",
"Newburn, Mammie",
"Newburn, Mann",
"Newburn Flowers, Marva Dyann",
"Newburn, Maurice Cleveland",
"Newburn, Megan",
"Newburn, Monica",
"Newburn Owens, Muareen",
"Newburn, Nala",
"Newburn, Quincy (LaFrances)",
"Newburn, Randall",
"Newburn, Reeyse",
"Newburn, Riley",
"Newburn, Robert",
"Newburn, Robin",
"Newburn Piggee, Rochell",
"Newburn, Thomas",
"Newburn, Tim",
"Newburn, Tish",
"Newburn Smth, Velma",
"Newburn, Walter",
"Newburn, Weslee Emma",
"Newburn, Willie Amos",
"Newburn Talley, Willye Mae",
"Newburn-Huntt, Latanji",
"Newburn-Williams, Brandi",
"Owens Newburn, Dorethia",
"Owens, Kirk",
"Parham, Burley Jean",
"Piggee, Krissen",
"Piggee, Xylen",
"Polite, Constance",
"Raney, Mary N",
"Richardson, Jackie Jerome",
"Richardson, Jaynie Carol",
"Russell, Cody",
"Russell, Jase A.",
"Sherman Wilson, Hazel",
"Silman, Mary Jane",
"Smith, Bennie",
"Dickerson Smith, Mary Beatrice",
"Smith Newburn, Mattie Rene",
"Smith, Roy",
"Stroope (White Slaver), Jacob",
"Talley, Johnny Talley, Jr.",
"Talley, Jonathan",
"Williams, Lula B",
"Wilson McCauley, Addie Sue",
"Wilson, Blake Andus",
"Newburn Wilson, Carola",
"Wilson, Darlene",
"Wilson, Donnie Ray",
"Wilson, Gabriel",
"Wilson, Gabriel I",
"Wilson Sen, Iris",
"Wilson Richarson, Jada",
"Wilson Clark, Janie B.",
"Wilson, Jasmine",
"Wilson, Jon Paul",
"Wilson, Lelani",
"Wilson, Levi",
"Wilson, Lillie Mae",
"Wilson, Marci",
"Wilson Davis, Rayvn",
"Wilson, Regina",
"Wilson, Richard",
"Wilson, Robert",
"Wilson, Robert III",
"Wilson, Robert Lawrence",
"Wilson Newburn, Ruby Lee",
"Wilson, Trevion",
"Wilson, Trevon",
"Wilson, Vernon",
"Wilson, Vivian Jacklyn",
"Wilson, Xavier",
"Wilson-Beattie, Robin L.",
"Yarber, Mildred"
]
Dwr.ScriptLoaded('dwr_db_I_short_name_0.js');
